In [ ]:
#Data okuyoruz
import pandas as pd
df = pd.read_csv("tr_yorumlar.csv")
df.shape



(567, 2)

In [ ]:
#Data değerleri kontrol ediyourz
df.head(10)

,yorum,duygu
0,Kugerr makine ve Marmaris servis Batu Ticaret ...,negative
1,ürün gayet iyi ama kurulum sıkıntılı,negative
2,fiyatına göre cok iyi montajı kendım yaptım s...,positive
3,"birkaç ay kullanıp atarsınız, malzeme kalitesi...",negative
4,"çok kötü bir film bence,ayrıca hiçte etkilenme...",negative
5,ürün güzel memnun kaldım teşekkür ediyorum hep...,positive
6,fiyatına göre iyi sadece plastik aksamları bir...,negative
7,"sanat için sanat derler ya, bu da vahset için ...",negative
8,kesinlikle vakit geçirmeye değmez. oldukça köt...,negative
9,"ürün 2 günde elime ulaştı, fiyatına göre alına...",positive


In [ ]:
#Null değerler ve type 
df.dtypes
df.isnull().sum()

yorum    0
duygu    0
dtype: int64

In [5]:
#Label dağılımı 
df["yorum"].value_counts()  # kolon adını kendi datana göre değiştir
df["duygu"].value_counts(normalize=True)

duygu
positive    0.504409
negative    0.495591
Name: proportion, dtype: float64

Label dağılım positive 51 negative 49 çıktı buda dengeli bir veri yapısı veriyor 

#Data genel değerlendirmesine bakıyoruz 
yorumlar ortlama uzunluğuna bakıyoruz datada çok kısa ve çok uzun cümleler var

In [ ]:

df["char_len"] = df["yorum"].str.len()  
df["word_len"] = df["yorum"].str.split().str.len()
df[["char_len","word_len"]].describe()

,char_len,word_len
count,567.000000,567.000000
mean,129.158730,18.365079
std,86.582542,12.072325
min,16.000000,1.000000
25%,56.000000,8.000000
50%,114.000000,16.000000
75%,179.000000,25.000000
max,393.000000,56.000000


In [7]:
df.duplicated().sum()
df["yorum"].duplicated().sum()

np.int64(0)

#En kısa ve en uzun yorumu kontrol ediyouz 
Çok kısa ve positive olanlar var ama çok kısa vee negative olanlarda var 

In [ ]:

df.loc[df["word_len"].idxmin(), "yorum"]
df.sort_values("word_len").head(5)[["yorum","duygu","word_len"]]

,yorum,duygu,word_len
511,"iyi...iyi...10/9,5",positive,1
324,gereksizlik abidesi.,negative,2
140,sesli çalışıyor.,negative,2
550,kullanamadım kiiiiiiiiiii,negative,2
89,fiyatı çok makul,positive,3


#Zıtlık bağlacını kontrol ediyourz
zıtlık bağlacı içeren yorumlar daha çok negative

In [ ]:

mask = df["yorum"].str.contains(r"\bama\b|\bfakat\b|\bancak\b", case=False, regex=True, na=False)
df[mask]["duygu"].value_counts(normalize=True)
print(mask.sum(), "yorumda zıtlık bağlacı var")

118 yorumda zıtlık bağlacı var


#Rastgele  verilere bakıyoruz data nasıl sekilleneceğine dair 
Burda yazım hataları ve farklı kategorilerden yorumlarda mevcut

In [ ]:

pd.set_option("display.max_colwidth", None)
for t in df[df["duygu"]=="negative"].sample(10, random_state=1)["yorum"]:
    print("-", t, "\n")

- en ufak kırıntıları,taşı,toprağı hiçbir şeyi çekmiyor. geri iade de edemedim. bunu alacağıma keşke uzatma kablosu ile basit bir ev elektrik süpürgesi alsaydım. çok daha memnun kalırdım. alan zarar eder. 

- masa ve kitalık bölümü çok küçük,görüntüye bakmayın 

- Plastik yapısı çok kırılgan. Her an başına birşey gelebilir diye kutuda gezdiriyorum. bilseydin bu kadar ince ve kırılgan olduğunu almazdım. 

- Tavsiye etmiyorum. Senaryo çok havada kalmış. Sonuda kötü yapılmış. Seyrettikten sonra hemen unutmak isteyeceğiniz bir film. 4/10 

- ya film için tek diğecek şeyim var oda çok sıkıcı olması.Nerdeyse uykum geliyordu.Bİraz da karışık olmasıve ve hiç heyecan olmaması uykum gelecek halini alıyor.Şiddetle tavsiye etmem.Ama inat edip izlemek istiyorum diyorsanız keyif sizin... 

- sıfır maliyetle ancak bu kadar film yapılırdı.filmde o kadar çok hata var ki saymakla bitmez.laptop parçalama sahnesi bile gerçek değildi.3 bile çok bence 

- arkadaşlar 9 ay kadar önce almıştım. 10400 mah değer

In [11]:
df.value_counts(normalize=True)

yorum                                                                                                                                                                                                    duygu     char_len  word_len
Kugerr makine ve Marmaris servis Batu Ticaret inanilmaz kotu.                                                                                                                                            negative  61        9           0.001764
ürün gayet iyi ama kurulum sıkıntılı                                                                                                                                                                     negative  36        6           0.001764
fiyatına göre cok iyi  montajı kendım yaptım sabahı bekleyemedım buyuklugu harıka                                                                                                                        positive  81        11          0.001764
birkaç ay kullanıp atarsınız, malzeme kalite

In [12]:
mask = df["yorum"].str.contains(r"\bama\b|\bfakat\b|\bancak\b", case=False, regex=True, na=False)
df[mask]["duygu"].value_counts(normalize=True)

duygu
negative    0.694915
positive    0.305085
Name: proportion, dtype: float64

In [13]:
pd.set_option("display.max_colwidth", None)
for t in df[df["duygu"]=="positive"].sample(10, random_state=1)["yorum"]:
    print("-", t, "\n")

- üründe herhangi bir sorun yok ve  aldıktan iki gün sonra bana teslim edildi çok hızlılar. 

- akıllı saat almak isteyenler düşünsün derim. fiyatı oldukça uygun. mağazalardan 200 lira daha ucuza aldım 

- Her şey çok iyiydi. Etstura teşekkür ederim onların tavsiye üzerine gittim mennunum. 

- bu fiyata ve kaliteli ürün kesinlikle alacak olanlara hiç düşünmeden almalarını tavsiye ederim. firmaya da hızlı kargo için teşekkür ederim. 

- kargosu çok hizli di̇yarbakir gi̇bi̇ yere 2 gunde geldi̇.apart sorunu var.netten i̇zledi̇ğm vi̇deolarda deği̇şi̇k aparatlardan bahsedi̇yordu.onlari da alinca artik si̇zi̇ kimse tutamaz.sessi̇z ve seri̇ çali̇isiyo.şi̇ddetle tavsiye ederi̇m 

- ürün süper hızlı gönderi olmasına rağmen 3.günde elime ulaştı. hepsiburada.com'dan müşteri hizmetleri gecikmeyle ilgili bildirimlerde bulundular. fakat benim için bir sonraki alışverişimi etkileyecek yönde bir deneyim oldu. ürüne gelince ürün yorumlarda da belirtildiği gibi fiyatına göre gayet ideal, kaliteli bir ür

#Küçük harf çevirme gibi işlemde lower yeine PyICU  kullandım küçük harf yaparken yakın harfleri farklı bir hafre cevirebilir diye
#Zıtlık bağlaç stopwords de ama ki gib işlemler normalde çıkarmamız gerekirken cümle içinde anlamına göre çıkarma uygulammız gerek
#Stemming/lemmatization yapımında ene yayın kullanılan zeyrek kullanabilirz n-gram işimizi görmeye bilir 
#Tekrarlayan harf ve noktalar kaldırdım 

In [ ]:
!pip install pipwin



[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
!pipwin install pyicu

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\data-science-project\data-science-project-54\.venv-1\Scripts\pipwin.exe\__main__.py", line 4, in <module>
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\pipwin\command.py", line 28, in <module>
    from . import pipwin, __version__
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\pipwin\pipwin.py", line 13, in <module>
    import js2py
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, Func

In [17]:
!pip install zeyrek


[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import re
import zeyrek



import logging
logging.getLogger("zeyrek").setLevel(logging.ERROR)
analyzer = zeyrek.MorphAnalyzer()

def preprocess(text: str) -> str:
   
    # 1 Türkçe Stop-Word listesi
    standart_stopwords = {
        "ve", "veya", "da", "de", "ile", "için", "çünkü", "bir", "bu", "şu", "o",
        "ki", "mi", "mı", "mu", "mü", "gibi", "hem", "ise", "diye", "en", "daha",
        "böyle", "şöyle", "her", "hiç", "bazı", "tüm", "hep", "kendi",
        "ama", "fakat", "lakin", "ancak", "oysa", "halbuki", "yine", "rağmen"
    }
    
    #Silinmesini istemediğimiz zıtlık bağlaçları
    korunacak_zitlik_baglaclari = {
        "ama", "fakat", "lakin", "ancak", "oysa", "halbuki", "yine", "rağmen", "oysaki"
    }
    
    # Filtre  oluşturma
    temizlik_listesi = standart_stopwords - korunacak_zitlik_baglaclari

    #Türkçe Uyumlu Küçük Harfe Çevirme 
    harf_haritasi = {'İ': 'i', 'I': 'ı'}
    metin = text
    for buyuk, kucuk in harf_haritasi.items():
        metin = metin.replace(buyuk, kucuk)
    metin = metin.lower()

    #  Tekrar eden Harfleri Normalize 
    metin = re.sub(r'(\w)\1{2,}', r'\1', metin)

    # --- ADIM 3: Noktalama Temizliği (URL, E-posta ve Sayı Korumalı) ---
    # E-posta ve URL'leri korumak için etiketleme
    urls = re.findall(r'https?://\S+|www\.\S+', metin)
    emails = re.findall(r'\S+@\S+', metin)
    
    for i, url in enumerate(urls):
        metin = metin.replace(url, f" [URL_{i}] ")
    for i, email in enumerate(emails):
        metin = metin.replace(email, f" [EMAIL_{i}] ")

    # Kelime başı/sonu ve bağımsız noktalama işaretlerini temizleme
    metin = re.sub(r'(?<!\w)[.,!?;:"\'()\[\]{}–\-—<>‘“’”（）«»*_+~`|=#]+', ' ', metin)
    metin = re.sub(r'[.,!?;:"\'()\[\]{}–\-—<>‘“’”（）«»*_+~`|=#]+(?!\w)', ' ', metin)
    metin = re.sub(r'\s+[.,!?;:"\'()\[\]{}–\-—<>‘“’”（）«»*_+~`|=#]+\s+', ' ', metin)

    # E-posta ve URL'leri geri yükleme
    for i, url in enumerate(urls):
        metin = metin.replace(f" [URL_{i}] ", url)
    for i, email in enumerate(emails):
        metin = metin.replace(f" [EMAIL_{i}] ", email)

    # Fazla boşlukları temizleme
    metin = re.sub(r'\s+', ' ', metin).strip()

    #  Zeyrek ile Tokenize ve Lemmatization -
    analiz_sonuclari = analyzer.analyze(metin)
    
    kok_kelimeler = []
    
    for kelime_analizi in analiz_sonuclari:
     if not kelime_analizi:
        continue

     en_olasi_analiz = kelime_analizi[0]
     orijinal_kelime = en_olasi_analiz.word.lower()
     kelime_koku = getattr(en_olasi_analiz, 'lemma', en_olasi_analiz).lower()

    # Zıtlık bağlaçlarında zeyrek'e güvenme, orijinali kullan
     if orijinal_kelime in korunacak_zitlik_baglaclari:
        kelime_koku = orijinal_kelime

    # Zeyrek tanıyamadıysa (Unk), orijinali kullan
     if kelime_koku == "unk":
        kelime_koku = orijinal_kelime

     if not kelime_koku.isalpha():
        continue

     if kelime_koku not in temizlik_listesi:
        kok_kelimeler.append(kelime_koku)  
    # Temizlenmiş metni birleştirerek döndür
    processed_text = " ".join(kok_kelimeler)
    return processed_text


Ön işleme fonksiyonu test etme 
Girinti hatası düzeltildi 
Bilinmeyen kelimlerde temizlendi

In [ ]:

for ornek in df["yorum"].head(5):
    print("ORİJİNAL:", ornek)
    print("İŞLENMİŞ:", preprocess(ornek))
    print()

ORİJİNAL: Kugerr makine ve Marmaris servis Batu Ticaret inanilmaz kotu.
İŞLENMİŞ: kugerr maki marmaris servis batu ticaret inanilmaz kot

ORİJİNAL: ürün gayet iyi ama kurulum sıkıntılı
İŞLENMİŞ: ürün gayet iyi ama kurul sıkıntı

ORİJİNAL: fiyatına göre cok iyi  montajı kendım yaptım sabahı bekleyemedım buyuklugu harıka
İŞLENMİŞ: fiyat göre cok iyi montaj kendım yapmak sabah bekleyemedım buyuklugu harıka

ORİJİNAL: birkaç ay kullanıp atarsınız, malzeme kalitesi çok kötü. suya giren bir ürün olduğu için paslanmaz olması gerekirken , vidaları paslanıyor ve elektrik bağlantıları kopuyor.
İŞLENMİŞ: birkaç ay kullanmak atmak malzeme kalite çok kötü su girmek ürün olmak paslanmaz olmak gerekmek vida paslanmak elektrik bağlantı kopmak

ORİJİNAL: çok kötü bir film bence,ayrıca hiçte etkilenmedim ama müzikleri çok güzel...
İŞLENMİŞ: çok kötü film bence ayrıca etkilemek ama müzik çok güzel



In [ ]:
sonuc = analyzer.analyze("ürün gayet iyi ama kurulum sıkıntılı")
print(len(sonuc))
print(sonuc[0])
print(dir(sonuc[0][0]))  
#hangi kelimelerde hata yaptığını yakalmaya calıstım

6
[Parse(word='ürün', lemma='ürün', pos='Noun', morphemes=['Noun', 'A3sg'], formatted='[ürün:Noun] ürün:Noun+A3sg'), Parse(word='ürün', lemma='ürümek', pos='Verb', morphemes=['Verb', 'Pass', 'Verb', 'Imp', 'A2sg'], formatted='[ürümek:Verb] ürü:Verb|n:Pass→Verb+Imp+A2sg')]
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__match_args__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_asdict', '_field_defaults', '_fields', '_make', '_replace', 'count', 'formatted', 'index', 'lemma', 'morphemes', 'pos', 'word']


In [ ]:
import time
başla = time.time()
df["yorum_temiz"] = df["yorum"].apply(preprocess)
print(f"Süre: {time.time() - başla:.1f} saniye")
#Süre testi

Süre: 10.0 saniye


In [22]:
(df["yorum_temiz"].str.strip() == "").sum()

np.int64(0)

In [23]:
df["temiz_word_len"] = df["yorum_temiz"].str.split().str.len()
df[["word_len","temiz_word_len"]].describe()

,word_len,temiz_word_len
count,567.000000,567.000000
mean,18.365079,15.368607
std,12.072325,10.038791
min,1.000000,1.000000
25%,8.000000,7.000000
50%,16.000000,14.000000
75%,25.000000,21.000000
max,56.000000,49.000000


#Trian Test Split
klasik yöntem 80 20 ayrıdım datayı 

In [ ]:

from sklearn.model_selection import train_test_split

X = df["yorum_temiz"]
y = df["duygu"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print(X_train.shape, X_test.shape)
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

(453,) (114,)
duygu
positive    0.503311
negative    0.496689
Name: proportion, dtype: float64
duygu
positive    0.508772
negative    0.491228
Name: proportion, dtype: float64


İlk yaklasım TF-IDF + Logistic Regression
`ngram_range=(1,2)` kullanıldı bazı duygu yapılarını daha iyi yaklaması için . `max_features=3000` ve `min_df=2` ile sözlüğü sınırlandırıldı.


In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(ngram_range=(1,2), max_features=3000, min_df=2)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print(X_train_tfidf.shape, X_test_tfidf.shape)

(453, 1132) (114, 1132)


In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, classification_report

logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train_tfidf, y_train)

y_pred_train = logreg.predict(X_train_tfidf)
y_pred_test = logreg.predict(X_test_tfidf)

f1_train = f1_score(y_train, y_pred_train, pos_label="positive")
f1_test = f1_score(y_test, y_pred_test, pos_label="positive")

print(f"Train F1: {f1_train:.3f}")
print(f"Test F1: {f1_test:.3f}")
print()
print(classification_report(y_test, y_pred_test))

Train F1: 0.937
Test F1: 0.813

              precision    recall  f1-score   support

    negative       0.84      0.73      0.78        56
    positive       0.77      0.86      0.81        58

    accuracy                           0.80       114
   macro avg       0.80      0.80      0.80       114
weighted avg       0.80      0.80      0.80       114



Train F1 = 0,937, Test F1 = 0,813. Aradaki fark (0,124) hafif bir overfitting'e işaret ediyor 

In [27]:
!pip install -U sentence-transformers



[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
from sentence_transformers import SentenceTransformer

model_name = "emrecan/bert-base-turkish-cased-mean-nli-stsb-tr"
embed_model = SentenceTransformer(model_name)

d:\data-science-project\data-science-project-54\.venv-1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3926.64it/s]


İkinci yaklasım  Türkçe BERT Embedding + Logistic Regression
İkinci yaklaşım için embedding modeline hafif  bir temizlik uyguluyoruz — TF-IDF'teki ağır ön işlemeden (stopword silme, lemmatization) kasıtlı olarak farklı. Çünkü BERT tabanlı modeller cümlenin bağlamından (kelime sırası, ekler, noktalama) faydalanıyor.

In [30]:
def hafif_temizle(text: str) -> str:
    metin = text.lower()  # Türkçe İ/ı sorunundan kaçınmak için istersen harf_haritasini burada da kullanabilirsin
    metin = re.sub(r'(\w)\1{2,}', r'\1', metin)  # tekrarlayan harfleri normalize et
    metin = re.sub(r'\s+', ' ', metin).strip()   # fazla boşlukları temizle
    return metin

df["yorum_hafif"] = df["yorum"].apply(hafif_temizle)

In [31]:
X_train_hafif = df.loc[X_train.index, "yorum_hafif"]
X_test_hafif = df.loc[X_test.index, "yorum_hafif"]

X_train_emb = embed_model.encode(X_train_hafif.tolist(), show_progress_bar=True)
X_test_emb = embed_model.encode(X_test_hafif.tolist(), show_progress_bar=True)

print(X_train_emb.shape, X_test_emb.shape)

Batches: 100%|██████████| 4/4 [00:47<00:00, 11.87s/it]

(453, 768) (114, 768)


In [32]:
logreg_emb = LogisticRegression(max_iter=1000, random_state=42)
logreg_emb.fit(X_train_emb, y_train)

y_pred_train_emb = logreg_emb.predict(X_train_emb)
y_pred_test_emb = logreg_emb.predict(X_test_emb)

f1_train_emb = f1_score(y_train, y_pred_train_emb, pos_label="positive")
f1_test_emb = f1_score(y_test, y_pred_test_emb, pos_label="positive")

print(f"Train F1 (embedding): {f1_train_emb:.3f}")
print(f"Test F1 (embedding): {f1_test_emb:.3f}")
print()
print(classification_report(y_test, y_pred_test_emb))

Train F1 (embedding): 1.000
Test F1 (embedding): 0.847

              precision    recall  f1-score   support

    negative       0.85      0.82      0.84        56
    positive       0.83      0.86      0.85        58

    accuracy                           0.84       114
   macro avg       0.84      0.84      0.84       114
weighted avg       0.84      0.84      0.84       114



### İlk embedding sonucu 
Train F1 = 1,000, Test F1 = 0,847. Train F1'in tam 1,000 olması ciddi bir overfitting işareti — model train verisindeki her örneği ayırt edebiliyor, bu da gerçek bir örüntü öğrenmekten çok ezberlemiş demek oluyor


### C parametresini deniyoruz
Varsayılan ayarla (C=1.0) eğitilen embedding modelinde Train F1 = 1.000 çıktı — yani model train verisini ezberlemiş. Bunun düzelip düzelmediğini görmek için kontrol ediyorum


In [ ]:
#Model ezberleyip ezberlemediği kontrol ediyoruz
for C in [0.01, 0.1, 1.0]:
    m = LogisticRegression(max_iter=1000, random_state=42, C=C)
    m.fit(X_train_emb, y_train)
    f1_tr = f1_score(y_train, m.predict(X_train_emb), pos_label="positive")
    f1_te = f1_score(y_test, m.predict(X_test_emb), pos_label="positive")
    print(f"C={C}: Train F1={f1_tr:.3f}, Test F1={f1_te:.3f}")

C=0.01: Train F1=0.915, Test F1=0.879
C=0.1: Train F1=0.985, Test F1=0.835
C=1.0: Train F1=1.000, Test F1=0.847


### Regularization (C) denemesi sonucu
| C | Train F1 | Test F1 |
|---|---|---|
| 0,01 | 0,915 | **0,879** |
| 0,1 | 0,985 | 0,835 |
| 1,0 | 1,000 | 0,847 |

C=0,01'de hem overfitting neredeyse ortadan kalkıyor (train-test farkı 0,15'ten 0,04'e düşüyor) hem de Test F1 en yüksek seviyeye çıkıyor. Bu en iyi model oluyor


In [34]:
logreg_emb_final = LogisticRegression(max_iter=1000, random_state=42, C=0.01)
logreg_emb_final.fit(X_train_emb, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",0.01
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",42
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mult

In [35]:
y_pred_final = logreg_emb_final.predict(X_test_emb)
print(classification_report(y_test, y_pred_final))

              precision    recall  f1-score   support

    negative       0.88      0.88      0.88        56
    positive       0.88      0.88      0.88        58

    accuracy                           0.88       114
   macro avg       0.88      0.88      0.88       114
weighted avg       0.88      0.88      0.88       114



### Final embedding modeli sonucu
C=0,01 ile eğitilen final modelde precision/recall/f1 her iki sınıf için de dengeli çıktı 

**Genel karşılaştırma:**

| Yaklaşım | Test F1 |
|---|---|
| TF-IDF + Logistic Regression | 0,813 |
| Embedding + Logistic Regression (C=0,01) | **0,879** |


## 5. Hata Analizi
Bu bölümde test setindeki yanlış sınıflanan yorumları üç gruba ayırıp inceliyorum: sadece TF-IDF'in yanıldığı, sadece embedding'in yanıldığı, ve ikisinin de yanıldığı yorumlar var bunları göstermek


In [ ]:
# Test setindeki orijinal yorumları da görebilmek için bir dataframe 
test_df = df.loc[X_test.index, ["yorum", "duygu"]].copy()
test_df["tfidf_tahmin"] = logreg.predict(X_test_tfidf)
test_df["embedding_tahmin"] = logreg_emb_final.predict(X_test_emb)

# Her iki model de yanılmış mı, yoksa sadece biri mi?
test_df["tfidf_dogru"] = test_df["duygu"] == test_df["tfidf_tahmin"]
test_df["embedding_dogru"] = test_df["duygu"] == test_df["embedding_tahmin"]

print("Sadece TF-IDF yanıldı:", ((~test_df["tfidf_dogru"]) & (test_df["embedding_dogru"])).sum())
print("Sadece Embedding yanıldı:", ((test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])).sum())
print("İkisi de yanıldı:", ((~test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])).sum())
print("İkisi de doğru:", ((test_df["tfidf_dogru"]) & (test_df["embedding_dogru"])).sum())

Sadece TF-IDF yanıldı: 16
Sadece Embedding yanıldı: 7
İkisi de yanıldı: 7
İkisi de doğru: 84


### Karşılaştırma sayıları
Test setindeki 114 yorumun: 84'ünde iki model de doğru, 16'sında sadece TF-IDF yanıldı (embedding düzeltti), 7'sinde sadece embedding yanıldı, 7'sinde ikisi de yanıldı. 16 vs 7 oranı, embedding'in TF-IDF'e göre net bir üstünlüğü olduğunu gösteriyor — şimdi bu gruplardaki örnekleri tek tek inceleyip örüntü arayacağım.


In [ ]:
#Karsılastırma 
pd.set_option("display.max_colwidth", None)
ikisi_de_yanildi = test_df[(~test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])]
for _, row in ikisi_de_yanildi.iterrows():
    print(f"Gerçek: {row['duygu']} | TFIDF: {row['tfidf_tahmin']} | Embedding: {row['embedding_tahmin']}")
    print(row["yorum"])
    print()

Gerçek: negative | TFIDF: positive | Embedding: positive
güzel bir  boya saçlarım eski doğallığına geri döndü. kendinizin uygulayabilmesi özellikle çok güzel bir özellik. tavsiye ediyorum. denerseniz neticeyi görürsünüz.

Gerçek: negative | TFIDF: positive | Embedding: positive
daha önce okey hisset ve rötar kullandım, onlar daha iyi performans sağlıyordu, ama buda fiyatına göre fena sayılmaz, yinede tavsiye edilebilir...

Gerçek: negative | TFIDF: positive | Embedding: positive
gerçekten fragmanı bile çok güzel merakla bekliyorum ...

Gerçek: negative | TFIDF: positive | Embedding: positive
arkadaşlar 9 ay kadar önce almıştım. 10400 mah değeri desteklemiyor ortalama 3000 mah' a sahip bir telefonu 3 defa deşarj halden full şarj yapması gerekirken 1 defa anca yapıyor. bazen 1 buçuk defa. ayrıca orjinal test kodunu sisteme girdiğim zaman daha önce 5 defa sorgulanmıştır diye bir ibare ile karşılaştım.

Gerçek: positive | TFIDF: negative | Embedding: negative
çok komik ve güzel çocuklugumu

### İkisi de yanılan örnekler
Bu grupta ilginç bir şey var: çoğu örnek aslında **açıkça pozitif okunan bir metin ama negative etiketlenmiş** (örn. "...tavsiye ediyorum. denerseniz neticeyi görürsünüz." → negative). Bu muhtemelen modelin hatası değil, **veri setindeki etiketleme gürültüsü** ya da kesik/eksik yorum metni — verinin kendi sınırlarını gösteren bir bulgu.


In [ ]:
#Tfıdf yanıldığı yerler 
sadece_tfidf_yanildi = test_df[(~test_df["tfidf_dogru"]) & (test_df["embedding_dogru"])]
for _, row in sadece_tfidf_yanildi.iterrows():
    print(f"Gerçek: {row['duygu']} | TFIDF tahmini: {row['tfidf_tahmin']}")
    print(row["yorum"])
    print()

Gerçek: positive | TFIDF tahmini: negative
Tek yapmanız gereken sponsorları takip etmek herkes açabildiği kadar fake açsın

Gerçek: negative | TFIDF tahmini: positive
Ya bi sktir sonradan görme varoş köpek

Gerçek: negative | TFIDF tahmini: positive
en ufak kırıntıları,taşı,toprağı hiçbir şeyi çekmiyor. geri iade de edemedim. bunu alacağıma keşke uzatma kablosu ile basit bir ev elektrik süpürgesi alsaydım. çok daha memnun kalırdım. alan zarar eder.

Gerçek: positive | TFIDF tahmini: negative
verilen parayi son kurusuna kadar hakeden bir urun

Gerçek: negative | TFIDF tahmini: positive
Kafanızın içinde beyin yerine bok var

Gerçek: negative | TFIDF tahmini: positive
taban kalitesiz, derisi yumuşak ve kalıp şekli çabuk bozuldu, 1 yıldır kullanıyorum, parası kadar ayakkabı, alternatifleri değerlendirin.

Gerçek: positive | TFIDF tahmini: negative
bu nedenle biraz daha bütçe ayırıp, lumia 640 serisinden bir model tercih edilmeli.

Gerçek: negative | TFIDF tahmini: positive
gereksız vasat v

tf-ıfd yanıldığı yerler 
-Argo Küfür olan yerde yanılıyor 
-Zıtlıklarda ve olumsuzlamada yanılıyor

In [ ]:
#Embeding yanıldığı yerler 
sadece_emb_yanildi = test_df[(test_df["tfidf_dogru"]) & (~test_df["embedding_dogru"])]
for _, row in sadece_emb_yanildi.iterrows():
    print(f"Gerçek: {row['duygu']} | Embedding tahmini: {row['embedding_tahmin']}")
    print(row["yorum"])
    print()

Gerçek: positive | Embedding tahmini: negative
Çok çok fazla çökmüş burada

Gerçek: positive | Embedding tahmini: negative
bu ağırlıklar bi harika dostum.boyası azcık özensiz azcık da dökülmüş gibi amma bu fiyata 2x5kg müthiş

Gerçek: negative | Embedding tahmini: positive
keanu reeves&#39;i matrix serisinden sonra gozumuzden dusmesini saglayan film(!)

Gerçek: positive | Embedding tahmini: negative
Tesıs guzel ama cok devasa buyuk oldugu ıcın ısıtma problemı vardı restorantı bıraz küçüktü yemek kalitesini düşük gördüm.

Gerçek: positive | Embedding tahmini: negative
buyuk olduğundan kullanışlı degil malesef. ancak bu fiyata gayet iyi.

Gerçek: positive | Embedding tahmini: negative
tabi bu seviyeye getirene kadar hata yaparsanız , veya şablona dikkatli bakmazsanız söküp tekrar takmak zorunda kalacaksınız ve o anlarda internetten aldığınıza pişman olabilirsiniz. ancak dikkatli ve 2-3 kişi yaparsanız sizin için daha hızlı ve rahat olur.

Gerçek: positive | Embedding tahmini: negative
ço

### Embedding'in yanıldığı yerler — zayıf yönü
Burada  yanıldığı örneklerin çoğu ters sıralı zıtlık cümleleri olumsuz başlayıp "ama/ancak" ile pozitife dönen cümleler. 

Bunun muhtemel sebebi: model, veride "ama/ancak"ın çoğunlukla negatife işaret ettiği genel örüntüyü çok iyi öğrenmiş (EDA'daki %69,5 bulgusu), ama bu örüntünün istisnalarında (nadir görülen ters sıralı cümlelerde) bu genellemeye fazla güvenip yanılıyor.

**Genel sonuç:** Embedding yöntemi, klasik yöntemin kaçırdığı bağlamsal ipuçlarını (negation, argo/küfür, cümle geneli) yakalayarak daha yüksek f1 elde ediyor, ama kendi öğrendiği istatistiksel örüntüye fazla bağlanabildiği durumlarda hataya düşüyor. Bu yüzden üretimde bu tip yorumları düşük güvenle işaretleyip insan gözden geçirmesine yönlendirmeli.
